package sec1_2;
/*
    1.2.27 Gaussian random numbers.
    Write a program that prints a random number 'r' drawn from the Gaussian distribution.
    One way to do so is to use the Box-Muller formula.

    r = sin(2 * PI * v) * (-2 * ln * u)^1/2

    Where 'u' and 'v' are real numbers between 0 and 1 generated by the Math.random() method.
 */
public class random_gaussian {
    public static void main(String[] args) {

        double u, v, r;

        u = Math.random();
        v = Math.random();
        System.out.print(String.format("%80s\n", " ").replace(" ", "*"));
        System.out.printf("u: %.2f\nv: %.2f\n\n  -- standard Gaussian (normal) distribution using the polar form of " +
                "the Box-Muller formula --\nr = sin(2 * PI * v) * (-2 * log(u))^1/2\n\n", u, v);
        r = Math.sin(2 * Math.PI * v) * Math.pow(-2 * Math.log(u), 0.5);
        System.out.printf("r = %.16f\n\n10 more iterations...\n", r);
        for(int i = 0; i < 10; i++) {
            u = Math.random();
            v = Math.random();
            System.out.print(String.format("%80s\n", " ").replace(" ", "-"));
            System.out.printf("| u = %.8f\n| v = %.8f\n|\n", u, v);
            r = Math.sin(2 * Math.PI * v) * Math.pow(-2 * Math.log(u), 0.5);
            System.out.printf("| r = %.16f\n", r);
            System.out.print(String.format("%80s\n\n", " ").replace(" ", "-"));
        }
        System.out.print(String.format("%80s\n", " ").replace(" ", "*"));

    }
}
